version: '3.7'

services:
  sprk-assignment:
    container_name: sprk-assignment
    build: .
    image: sprk-assignment:latest
    restart: always
    network_mode: host
    ports:
      - 8000:8000

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    network_mode: host
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sprk
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      DATABASE_URL: postgresql://myuser:mypass@localhost:5432/sprk
